application: arkc-gae
module: register
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: register.main
  secure: optional

libraries:
- name: pycrypto
  version: "latest"
