application: arkc-gae
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots.txt
  script: version.application
  
- url: /.*
  script: register.app

libraries:
- name: webapp2
  version: "latest"
